insert into Course (CourseID, Title, Credits) values (1, 'Sales', 7);
insert into Course (CourseID, Title, Credits) values (2, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (3, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (4, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (5, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (6, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (7, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (8, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (9, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (10, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (11, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (12, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (13, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (14, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (15, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (16, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (17, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (18, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (19, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (20, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (21, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (22, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (23, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (24, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (25, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (26, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (27, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (28, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (29, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (30, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (31, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (32, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (33, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (34, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (35, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (36, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (37, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (38, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (39, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (40, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (41, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (42, 'Research and Development', 8);
insert into Course (CourseID, Title, Credits) values (43, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (44, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (45, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (46, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (47, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (48, 'Support', 10);
insert into Course (CourseID, Title, Credits) values (49, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (50, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (51, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (52, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (53, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (54, 'Accounting', 3);
insert into Course (CourseID, Title, Credits) values (55, 'Sales', 7);
insert into Course (CourseID, Title, Credits) values (56, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (57, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (58, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (59, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (60, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (61, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (62, 'Legal', 7);
insert into Course (CourseID, Title, Credits) values (63, 'Marketing', 7);
insert into Course (CourseID, Title, Credits) values (64, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (65, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (66, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (67, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (68, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (69, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (70, 'Sales', 10);
insert into Course (CourseID, Title, Credits) values (71, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (72, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (73, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (74, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (75, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (76, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (77, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (78, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (79, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (80, 'Engineering', 10);
insert into Course (CourseID, Title, Credits) values (81, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (82, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (83, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (84, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (85, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (86, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (87, 'Sales', 1);
insert into Course (CourseID, Title, Credits) values (88, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (89, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (90, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (91, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (92, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (93, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (94, 'Services', 8);
insert into Course (CourseID, Title, Credits) values (95, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (96, 'Marketing', 7);
insert into Course (CourseID, Title, Credits) values (97, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (98, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (99, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (100, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (101, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (102, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (103, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (104, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (105, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (106, 'Research and Development', 8);
insert into Course (CourseID, Title, Credits) values (107, 'Sales', 10);
insert into Course (CourseID, Title, Credits) values (108, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (109, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (110, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (111, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (112, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (113, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (114, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (115, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (116, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (117, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (118, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (119, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (120, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (121, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (122, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (123, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (124, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (125, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (126, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (127, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (128, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (129, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (130, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (131, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (132, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (133, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (134, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (135, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (136, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (137, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (138, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (139, 'Legal', 10);
insert into Course (CourseID, Title, Credits) values (140, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (141, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (142, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (143, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (144, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (145, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (146, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (147, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (148, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (149, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (150, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (151, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (152, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (153, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (154, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (155, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (156, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (157, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (158, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (159, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (160, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (161, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (162, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (163, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (164, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (165, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (166, 'Legal', 10);
insert into Course (CourseID, Title, Credits) values (167, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (168, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (169, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (170, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (171, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (172, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (173, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (174, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (175, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (176, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (177, 'Services', 8);
insert into Course (CourseID, Title, Credits) values (178, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (179, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (180, 'Human Resources', 4);
insert into Course (CourseID, Title, Credits) values (181, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (182, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (183, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (184, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (185, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (186, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (187, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (188, 'Legal', 10);
insert into Course (CourseID, Title, Credits) values (189, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (190, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (191, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (192, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (193, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (194, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (195, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (196, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (197, 'Accounting', 2);
insert into Course (CourseID, Title, Credits) values (198, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (199, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (200, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (201, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (202, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (203, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (204, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (205, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (206, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (207, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (208, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (209, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (210, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (211, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (212, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (213, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (214, 'Legal', 7);
insert into Course (CourseID, Title, Credits) values (215, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (216, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (217, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (218, 'Services', 5);
insert into Course (CourseID, Title, Credits) values (219, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (220, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (221, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (222, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (223, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (224, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (225, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (226, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (227, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (228, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (229, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (230, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (231, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (232, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (233, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (234, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (235, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (236, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (237, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (238, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (239, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (240, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (241, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (242, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (243, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (244, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (245, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (246, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (247, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (248, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (249, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (250, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (251, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (252, 'Legal', 7);
insert into Course (CourseID, Title, Credits) values (253, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (254, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (255, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (256, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (257, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (258, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (259, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (260, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (261, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (262, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (263, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (264, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (265, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (266, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (267, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (268, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (269, 'Sales', 10);
insert into Course (CourseID, Title, Credits) values (270, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (271, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (272, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (273, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (274, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (275, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (276, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (277, 'Business Development', 9);
insert into Course (CourseID, Title, Credits) values (278, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (279, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (280, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (281, 'Product Management', 3);
insert into Course (CourseID, Title, Credits) values (282, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (283, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (284, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (285, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (286, 'Accounting', 1);
insert into Course (CourseID, Title, Credits) values (287, 'Accounting', 1);
insert into Course (CourseID, Title, Credits) values (288, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (289, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (290, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (291, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (292, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (293, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (294, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (295, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (296, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (297, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (298, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (299, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (300, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (301, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (302, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (303, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (304, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (305, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (306, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (307, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (308, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (309, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (310, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (311, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (312, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (313, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (314, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (315, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (316, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (317, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (318, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (319, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (320, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (321, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (322, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (323, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (324, 'Accounting', 2);
insert into Course (CourseID, Title, Credits) values (325, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (326, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (327, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (328, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (329, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (330, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (331, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (332, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (333, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (334, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (335, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (336, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (337, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (338, 'Marketing', 7);
insert into Course (CourseID, Title, Credits) values (339, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (340, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (341, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (342, 'Human Resources', 7);
insert into Course (CourseID, Title, Credits) values (343, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (344, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (345, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (346, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (347, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (348, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (349, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (350, 'Accounting', 3);
insert into Course (CourseID, Title, Credits) values (351, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (352, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (353, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (354, 'Services', 8);
insert into Course (CourseID, Title, Credits) values (355, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (356, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (357, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (358, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (359, 'Marketing', 7);
insert into Course (CourseID, Title, Credits) values (360, 'Research and Development', 8);
insert into Course (CourseID, Title, Credits) values (361, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (362, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (363, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (364, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (365, 'Legal', 10);
insert into Course (CourseID, Title, Credits) values (366, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (367, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (368, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (369, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (370, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (371, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (372, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (373, 'Business Development', 9);
insert into Course (CourseID, Title, Credits) values (374, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (375, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (376, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (377, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (378, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (379, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (380, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (381, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (382, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (383, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (384, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (385, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (386, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (387, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (388, 'Human Resources', 4);
insert into Course (CourseID, Title, Credits) values (389, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (390, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (391, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (392, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (393, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (394, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (395, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (396, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (397, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (398, 'Business Development', 9);
insert into Course (CourseID, Title, Credits) values (399, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (400, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (401, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (402, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (403, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (404, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (405, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (406, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (407, 'Training', 3);
insert into Course (CourseID, Title, Credits) values (408, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (409, 'Business Development', 9);
insert into Course (CourseID, Title, Credits) values (410, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (411, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (412, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (413, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (414, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (415, 'Research and Development', 8);
insert into Course (CourseID, Title, Credits) values (416, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (417, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (418, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (419, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (420, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (421, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (422, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (423, 'Legal', 7);
insert into Course (CourseID, Title, Credits) values (424, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (425, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (426, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (427, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (428, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (429, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (430, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (431, 'Product Management', 6);
insert into Course (CourseID, Title, Credits) values (432, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (433, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (434, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (435, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (436, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (437, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (438, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (439, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (440, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (441, 'Engineering', 10);
insert into Course (CourseID, Title, Credits) values (442, 'Services', 5);
insert into Course (CourseID, Title, Credits) values (443, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (444, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (445, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (446, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (447, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (448, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (449, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (450, 'Sales', 7);
insert into Course (CourseID, Title, Credits) values (451, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (452, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (453, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (454, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (455, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (456, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (457, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (458, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (459, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (460, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (461, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (462, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (463, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (464, 'Training', 3);
insert into Course (CourseID, Title, Credits) values (465, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (466, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (467, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (468, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (469, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (470, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (471, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (472, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (473, 'Human Resources', 4);
insert into Course (CourseID, Title, Credits) values (474, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (475, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (476, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (477, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (478, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (479, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (480, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (481, 'Engineering', 10);
insert into Course (CourseID, Title, Credits) values (482, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (483, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (484, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (485, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (486, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (487, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (488, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (489, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (490, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (491, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (492, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (493, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (494, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (495, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (496, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (497, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (498, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (499, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (500, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (501, 'Accounting', 2);
insert into Course (CourseID, Title, Credits) values (502, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (503, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (504, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (505, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (506, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (507, 'Services', 7);
insert into Course (CourseID, Title, Credits) values (508, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (509, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (510, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (511, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (512, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (513, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (514, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (515, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (516, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (517, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (518, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (519, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (520, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (521, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (522, 'Sales', 1);
insert into Course (CourseID, Title, Credits) values (523, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (524, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (525, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (526, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (527, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (528, 'Engineering', 8);
insert into Course (CourseID, Title, Credits) values (529, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (530, 'Engineering', 10);
insert into Course (CourseID, Title, Credits) values (531, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (532, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (533, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (534, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (535, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (536, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (537, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (538, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (539, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (540, 'Services', 5);
insert into Course (CourseID, Title, Credits) values (541, 'Product Management', 3);
insert into Course (CourseID, Title, Credits) values (542, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (543, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (544, 'Support', 10);
insert into Course (CourseID, Title, Credits) values (545, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (546, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (547, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (548, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (549, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (550, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (551, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (552, 'Sales', 1);
insert into Course (CourseID, Title, Credits) values (553, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (554, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (555, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (556, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (557, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (558, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (559, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (560, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (561, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (562, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (563, 'Support', 10);
insert into Course (CourseID, Title, Credits) values (564, 'Product Management', 7);
insert into Course (CourseID, Title, Credits) values (565, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (566, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (567, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (568, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (569, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (570, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (571, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (572, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (573, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (574, 'Product Management', 5);
insert into Course (CourseID, Title, Credits) values (575, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (576, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (577, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (578, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (579, 'Services', 10);
insert into Course (CourseID, Title, Credits) values (580, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (581, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (582, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (583, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (584, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (585, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (586, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (587, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (588, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (589, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (590, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (591, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (592, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (593, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (594, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (595, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (596, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (597, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (598, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (599, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (600, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (601, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (602, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (603, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (604, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (605, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (606, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (607, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (608, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (609, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (610, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (611, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (612, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (613, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (614, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (615, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (616, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (617, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (618, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (619, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (620, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (621, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (622, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (623, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (624, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (625, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (626, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (627, 'Services', 4);
insert into Course (CourseID, Title, Credits) values (628, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (629, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (630, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (631, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (632, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (633, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (634, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (635, 'Training', 3);
insert into Course (CourseID, Title, Credits) values (636, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (637, 'Accounting', 2);
insert into Course (CourseID, Title, Credits) values (638, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (639, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (640, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (641, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (642, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (643, 'Accounting', 1);
insert into Course (CourseID, Title, Credits) values (644, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (645, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (646, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (647, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (648, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (649, 'Human Resources', 4);
insert into Course (CourseID, Title, Credits) values (650, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (651, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (652, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (653, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (654, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (655, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (656, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (657, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (658, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (659, 'Research and Development', 8);
insert into Course (CourseID, Title, Credits) values (660, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (661, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (662, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (663, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (664, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (665, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (666, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (667, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (668, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (669, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (670, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (671, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (672, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (673, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (674, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (675, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (676, 'Support', 10);
insert into Course (CourseID, Title, Credits) values (677, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (678, 'Product Management', 3);
insert into Course (CourseID, Title, Credits) values (679, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (680, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (681, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (682, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (683, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (684, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (685, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (686, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (687, 'Support', 8);
insert into Course (CourseID, Title, Credits) values (688, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (689, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (690, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (691, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (692, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (693, 'Accounting', 2);
insert into Course (CourseID, Title, Credits) values (694, 'Human Resources', 7);
insert into Course (CourseID, Title, Credits) values (695, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (696, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (697, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (698, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (699, 'Training', 8);
insert into Course (CourseID, Title, Credits) values (700, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (701, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (702, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (703, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (704, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (705, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (706, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (707, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (708, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (709, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (710, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (711, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (712, 'Training', 3);
insert into Course (CourseID, Title, Credits) values (713, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (714, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (715, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (716, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (717, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (718, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (719, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (720, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (721, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (722, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (723, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (724, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (725, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (726, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (727, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (728, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (729, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (730, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (731, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (732, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (733, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (734, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (735, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (736, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (737, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (738, 'Research and Development', 10);
insert into Course (CourseID, Title, Credits) values (739, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (740, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (741, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (742, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (743, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (744, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (745, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (746, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (747, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (748, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (749, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (750, 'Human Resources', 7);
insert into Course (CourseID, Title, Credits) values (751, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (752, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (753, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (754, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (755, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (756, 'Legal', 10);
insert into Course (CourseID, Title, Credits) values (757, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (758, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (759, 'Product Management', 2);
insert into Course (CourseID, Title, Credits) values (760, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (761, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (762, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (763, 'Accounting', 1);
insert into Course (CourseID, Title, Credits) values (764, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (765, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (766, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (767, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (768, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (769, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (770, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (771, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (772, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (773, 'Research and Development', 10);
insert into Course (CourseID, Title, Credits) values (774, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (775, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (776, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (777, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (778, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (779, 'Support', 10);
insert into Course (CourseID, Title, Credits) values (780, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (781, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (782, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (783, 'Legal', 1);
insert into Course (CourseID, Title, Credits) values (784, 'Sales', 6);
insert into Course (CourseID, Title, Credits) values (785, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (786, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (787, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (788, 'Support', 7);
insert into Course (CourseID, Title, Credits) values (789, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (790, 'Marketing', 7);
insert into Course (CourseID, Title, Credits) values (791, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (792, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (793, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (794, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (795, 'Support', 1);
insert into Course (CourseID, Title, Credits) values (796, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (797, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (798, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (799, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (800, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (801, 'Services', 8);
insert into Course (CourseID, Title, Credits) values (802, 'Research and Development', 1);
insert into Course (CourseID, Title, Credits) values (803, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (804, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (805, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (806, 'Business Development', 9);
insert into Course (CourseID, Title, Credits) values (807, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (808, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (809, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (810, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (811, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (812, 'Sales', 9);
insert into Course (CourseID, Title, Credits) values (813, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (814, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (815, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (816, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (817, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (818, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (819, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (820, 'Human Resources', 10);
insert into Course (CourseID, Title, Credits) values (821, 'Sales', 8);
insert into Course (CourseID, Title, Credits) values (822, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (823, 'Business Development', 2);
insert into Course (CourseID, Title, Credits) values (824, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (825, 'Research and Development', 10);
insert into Course (CourseID, Title, Credits) values (826, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (827, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (828, 'Support', 9);
insert into Course (CourseID, Title, Credits) values (829, 'Human Resources', 3);
insert into Course (CourseID, Title, Credits) values (830, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (831, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (832, 'Services', 8);
insert into Course (CourseID, Title, Credits) values (833, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (834, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (835, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (836, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (837, 'Support', 5);
insert into Course (CourseID, Title, Credits) values (838, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (839, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (840, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (841, 'Research and Development', 10);
insert into Course (CourseID, Title, Credits) values (842, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (843, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (844, 'Research and Development', 5);
insert into Course (CourseID, Title, Credits) values (845, 'Engineering', 2);
insert into Course (CourseID, Title, Credits) values (846, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (847, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (848, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (849, 'Marketing', 3);
insert into Course (CourseID, Title, Credits) values (850, 'Marketing', 1);
insert into Course (CourseID, Title, Credits) values (851, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (852, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (853, 'Accounting', 8);
insert into Course (CourseID, Title, Credits) values (854, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (855, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (856, 'Marketing', 6);
insert into Course (CourseID, Title, Credits) values (857, 'Training', 4);
insert into Course (CourseID, Title, Credits) values (858, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (859, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (860, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (861, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (862, 'Support', 2);
insert into Course (CourseID, Title, Credits) values (863, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (864, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (865, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (866, 'Human Resources', 4);
insert into Course (CourseID, Title, Credits) values (867, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (868, 'Training', 10);
insert into Course (CourseID, Title, Credits) values (869, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (870, 'Research and Development', 4);
insert into Course (CourseID, Title, Credits) values (871, 'Marketing', 4);
insert into Course (CourseID, Title, Credits) values (872, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (873, 'Support', 6);
insert into Course (CourseID, Title, Credits) values (874, 'Training', 5);
insert into Course (CourseID, Title, Credits) values (875, 'Sales', 3);
insert into Course (CourseID, Title, Credits) values (876, 'Sales', 5);
insert into Course (CourseID, Title, Credits) values (877, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (878, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (879, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (880, 'Research and Development', 7);
insert into Course (CourseID, Title, Credits) values (881, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (882, 'Engineering', 7);
insert into Course (CourseID, Title, Credits) values (883, 'Marketing', 8);
insert into Course (CourseID, Title, Credits) values (884, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (885, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (886, 'Support', 3);
insert into Course (CourseID, Title, Credits) values (887, 'Sales', 10);
insert into Course (CourseID, Title, Credits) values (888, 'Sales', 7);
insert into Course (CourseID, Title, Credits) values (889, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (890, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (891, 'Services', 5);
insert into Course (CourseID, Title, Credits) values (892, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (893, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (894, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (895, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (896, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (897, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (898, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (899, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (900, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (901, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (902, 'Legal', 5);
insert into Course (CourseID, Title, Credits) values (903, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (904, 'Research and Development', 3);
insert into Course (CourseID, Title, Credits) values (905, 'Research and Development', 6);
insert into Course (CourseID, Title, Credits) values (906, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (907, 'Services', 5);
insert into Course (CourseID, Title, Credits) values (908, 'Engineering', 5);
insert into Course (CourseID, Title, Credits) values (909, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (910, 'Engineering', 4);
insert into Course (CourseID, Title, Credits) values (911, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (912, 'Engineering', 3);
insert into Course (CourseID, Title, Credits) values (913, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (914, 'Services', 1);
insert into Course (CourseID, Title, Credits) values (915, 'Accounting', 7);
insert into Course (CourseID, Title, Credits) values (916, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (917, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (918, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (919, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (920, 'Business Development', 10);
insert into Course (CourseID, Title, Credits) values (921, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (922, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (923, 'Human Resources', 7);
insert into Course (CourseID, Title, Credits) values (924, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (925, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (926, 'Business Development', 3);
insert into Course (CourseID, Title, Credits) values (927, 'Sales', 1);
insert into Course (CourseID, Title, Credits) values (928, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (929, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (930, 'Research and Development', 2);
insert into Course (CourseID, Title, Credits) values (931, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (932, 'Legal', 3);
insert into Course (CourseID, Title, Credits) values (933, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (934, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (935, 'Training', 9);
insert into Course (CourseID, Title, Credits) values (936, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (937, 'Accounting', 4);
insert into Course (CourseID, Title, Credits) values (938, 'Support', 4);
insert into Course (CourseID, Title, Credits) values (939, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (940, 'Business Development', 1);
insert into Course (CourseID, Title, Credits) values (941, 'Training', 6);
insert into Course (CourseID, Title, Credits) values (942, 'Accounting', 9);
insert into Course (CourseID, Title, Credits) values (943, 'Training', 2);
insert into Course (CourseID, Title, Credits) values (944, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (945, 'Services', 9);
insert into Course (CourseID, Title, Credits) values (946, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (947, 'Marketing', 10);
insert into Course (CourseID, Title, Credits) values (948, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (949, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (950, 'Product Management', 10);
insert into Course (CourseID, Title, Credits) values (951, 'Training', 1);
insert into Course (CourseID, Title, Credits) values (952, 'Sales', 2);
insert into Course (CourseID, Title, Credits) values (953, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (954, 'Human Resources', 1);
insert into Course (CourseID, Title, Credits) values (955, 'Legal', 6);
insert into Course (CourseID, Title, Credits) values (956, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (957, 'Product Management', 1);
insert into Course (CourseID, Title, Credits) values (958, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (959, 'Product Management', 4);
insert into Course (CourseID, Title, Credits) values (960, 'Accounting', 5);
insert into Course (CourseID, Title, Credits) values (961, 'Human Resources', 2);
insert into Course (CourseID, Title, Credits) values (962, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (963, 'Marketing', 2);
insert into Course (CourseID, Title, Credits) values (964, 'Accounting', 3);
insert into Course (CourseID, Title, Credits) values (965, 'Business Development', 4);
insert into Course (CourseID, Title, Credits) values (966, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (967, 'Legal', 8);
insert into Course (CourseID, Title, Credits) values (968, 'Human Resources', 8);
insert into Course (CourseID, Title, Credits) values (969, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (970, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (971, 'Business Development', 5);
insert into Course (CourseID, Title, Credits) values (972, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (973, 'Engineering', 6);
insert into Course (CourseID, Title, Credits) values (974, 'Product Management', 8);
insert into Course (CourseID, Title, Credits) values (975, 'Business Development', 6);
insert into Course (CourseID, Title, Credits) values (976, 'Accounting', 10);
insert into Course (CourseID, Title, Credits) values (977, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (978, 'Legal', 2);
insert into Course (CourseID, Title, Credits) values (979, 'Sales', 4);
insert into Course (CourseID, Title, Credits) values (980, 'Research and Development', 9);
insert into Course (CourseID, Title, Credits) values (981, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (982, 'Product Management', 9);
insert into Course (CourseID, Title, Credits) values (983, 'Training', 7);
insert into Course (CourseID, Title, Credits) values (984, 'Legal', 4);
insert into Course (CourseID, Title, Credits) values (985, 'Business Development', 8);
insert into Course (CourseID, Title, Credits) values (986, 'Services', 2);
insert into Course (CourseID, Title, Credits) values (987, 'Human Resources', 9);
insert into Course (CourseID, Title, Credits) values (988, 'Engineering', 1);
insert into Course (CourseID, Title, Credits) values (989, 'Marketing', 9);
insert into Course (CourseID, Title, Credits) values (990, 'Accounting', 6);
insert into Course (CourseID, Title, Credits) values (991, 'Human Resources', 6);
insert into Course (CourseID, Title, Credits) values (992, 'Engineering', 9);
insert into Course (CourseID, Title, Credits) values (993, 'Business Development', 7);
insert into Course (CourseID, Title, Credits) values (994, 'Services', 6);
insert into Course (CourseID, Title, Credits) values (995, 'Marketing', 5);
insert into Course (CourseID, Title, Credits) values (996, 'Legal', 9);
insert into Course (CourseID, Title, Credits) values (997, 'Services', 3);
insert into Course (CourseID, Title, Credits) values (998, 'Human Resources', 5);
insert into Course (CourseID, Title, Credits) values (999, 'Engineering', 10);
insert into Course (CourseID, Title, Credits) values (1000, 'Services', 7);
